### ISSUE TITLE
How folks can become SMEs and interviewers

### ISSUE THREAD

**Issue by theresaanna** [18F/engineering-team-faq#4]
https://github.com/18F/engineering-team-faq/blob/master/for-eng-team-members.md#how-can-i-participate-in-resume-review-and-candidate-interviewing

@hollyallen: do we have a better answer for this question now? Should the person go directly to TT?

**Comment by hollyallen** [comment]
Updated! I think going to TT is good, since that's how they can become a resumer reviewer. We are also working on documentation and trainings. We want to do the training with Learn eventually, but for a while they will probably just be a meeting with me and Esther.
